FROM node:alpine AS base

WORKDIR /client
COPY . .
WORKDIR /client/UI
RUN npm install && npm run build

FROM golang:alpine

WORKDIR /client
COPY --from=base /client .
RUN adduser -D drf
USER drf

CMD go run main.go