version: "3.3"

services: 

  client:
    stdin_open: true
    build: 
      context: client
      dockerfile: Dockerfile.client
    ports: 
      - "3000:3000"
    volumes:
      - "/client"

  server:
    stdin_open: true
    build: 
      context: server
      dockerfile: Dockerfile.server
    ports: 
      - "3010:3010"
    volumes:
      - "/server"